# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  schedule:
    # Desired timezone: "Europe/Madrid" # In case it is used, from https://unix.stackexchange.com/a/504044/260613
    - cron:  '0 7-22 * * 1-6' # Every hour between 8 and 23 from Monday to Saturday

name: twitter-hourly
env:
  TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
  TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
  TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
  TWITTER_ACCESS_SECRET_TOKEN: ${{ secrets.TWITTER_ACCESS_SECRET_TOKEN }}

jobs:
  twitter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install system dependencies
        run:  sudo apt-get install libcurl4-openssl-dev
      - name: Cache R packages # From https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml#L50-L56
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: Install dependencies
        # if: ${{ failure() }} # https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsif
        run: |
          Rscript -e "install.packages(c('remotes'));
          remotes::install_github('rOpenSpain/BOE');
          install.packages('rtweet');
          install.packages('poorman')"
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: post-hourly.yaml
          name: update
          workflow_conclusion: success
      - name: run BOE
        run: Rscript news_BOE.R
      - name: Save remaining
        uses: actions/upload-artifact@v2
        with:
          name: update
          path: boe-hoy.RDS
