# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  schedule:
    # Desired timezone: "Europe/Madrid" # In case it is used, from https://unix.stackexchange.com/a/504044/260613
    - cron:  '40 5 * * *' # Every day at 7:40 Spain time, be aware of time changes

name: update-latest-journal

jobs:
  R-CMD-check:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install dependencies
        run: Rscript -e "install.packages(c('remotes')); remotes::install_github('rOpenSpain/BOE'); install.packages('rmarkdown');install.packages('dplyr');install.packages('ggalluvial');install.packages('forcats');install.packages('patchwork');install.packages('DT');install.packages('rtweet')"
      - name: Update
        run: Rscript last
      - name: git config
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'gh-pages committer'
      - name: Commit results
        run: |
          git add -A .
          git commit -m 'Automatic commit to update last BOE and BORME'
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.APPTOKEN }}

