# For help debugging build failures open an issue on the RStudio community with the 'github-actions' tag.
# https://community.rstudio.com/new-topic?category=Package%20development&tags=github-actions


on:
  push:
    branches:
      - main
      - master
  schedule:
    # Desired timezone: "Europe/Madrid" # In case it is used, from https://unix.stackexchange.com/a/504044/260613
    - cron:  '40 6 * * *' # Every day at 7:40 Spain time, be aware of time changes

name: update-latest-journal

jobs:
  setup:
    if: "! contains(github.event.commits.*.message, 'skip ci')"
    runs-on: ubuntu-latest
    env:
      TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
      TWITTER_API_SECRET_KEY: ${{ secrets.TWITTER_API_SECRET_KEY }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_SECRET_TOKEN: ${{ secrets.TWITTER_ACCESS_SECRET_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@master
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install system dependencies
        run:  sudo apt-get install libcurl4-openssl-dev
      - name: Install dependencies
        run: |
          Rscript -e "install.packages(c('remotes'));
          remotes::install_github('rOpenSpain/BOE');
          install.packages('rmarkdown');
          install.packages('dplyr');
          install.packages('ggalluvial');
          install.packages('forcats');
          install.packages('DT');
          install.packages('rtweet');
          install.packages('ggfittext')"
      - name: Cache R packages # From https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml#L50-L56
        if: runner.os != 'Windows'
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
      - name: git config
        run: |
          git config --global user.email 'actions@github.com'
          git config --global user.name 'gh-pages committer'
  update-boe:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Update
      run: Rscript last_BOE
    - name: Upload images
      uses: actions/upload-artifact@v2
      with:
        name: BOE-graphics
        path: docs/last_BOE_files/figure-html/
    - name: Upload web
      uses: actions/upload-artifact@v2
      with:
        name: BOE-web
        path: docs/last_BOE.html

  update-borme:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - name: Update
        run: Rscript last_BORME.R
      - name: Upload images
        uses: actions/upload-artifact@v2
        with:
          name: BORME-images
          path: docs/last_BORME_files/figure-html/
      - name: Upload artifacts 2
        uses: actions/upload-artifact@v2
        with:
          name: BORME-web
          path: docs/last_BORME.html
  push:
    runs-on: ubuntu-latest
    needs: [update-boe, update-borme]
    if: always()
    steps:
      - name: Download BOE images
        uses: actions/download-artifact@v2
        with:
          name: BOE-graphics
          path: docs/last_BOE_files/figure-html/
      - name: Download BOE webpage
        uses: actions/download-artifact@v2
        with:
          name: BOE-web
          path: docs/last_BOE.html
      - name: Download BORME images
        uses: actions/download-artifact@v2
        with:
          name: BORME-images
          path: docs/last_BORME_files/figure-html/
      - name: Download BORME webpage
        uses: actions/download-artifact@v2
        with:
          name: BORME-web
          path: docs/last_BORME.html
      - name: Commit results
        run: |
          git add -A .
          git commit -m 'Automatic commit to update last BOE and/or BORME'
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.APPTOKEN }}

